### ISSUE TITLE
Bug: Opening link in reader view and returning scrolls view

### ISSUE THREAD

**Issue by Limero** [Pocket/pocket-ios#1089]
Whenever I click a link in the reader view and then go back to the reader, the whole view scrolls up. This is very annoying when wanting to continue to read from the point where the link was.

I've attached a recording of the bug.

https://github.com/user-attachments/assets/dccc6dfd-908d-4a54-bf17-2620badcffc5

**Comment by Gio2018** [comment]
Hey thank you so much for filing this one! A fix is underway and will be available in the next release.

**Comment by Gio2018** [comment]
This bug is fixed in[ 8.21.0](https://github.com/Pocket/pocket-ios/releases/tag/release%2F8.21.0)
